! (C) Copyright 2014- ECMWF.
! (C) Copyright 2022- NVIDIA.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE TPM_FFTC

!   Author.
!   -------
!     George Mozdzynski
!
!   Modifications.
!   -------------- 
!     Original      October 2014

USE, INTRINSIC :: ISO_C_BINDING
USE GROWING_ALLOCATOR_MOD, ONLY: GROWING_ALLOCATION_TYPE
USE ISO_C_BINDING, ONLY: C_INT8_T

IMPLICIT NONE

SAVE

PRIVATE
PUBLIC EXECUTE_DIR_FFT, EXECUTE_INV_FFT, PLAN_DIR_FFT, PLAN_INV_FFT, FFTTMPBUFFER

INTERFACE EXECUTE_DIR_FFT
  MODULE PROCEDURE EXECUTE_DIR_FFT_FLOAT
  MODULE PROCEDURE EXECUTE_DIR_FFT_DOUBLE
END INTERFACE

INTERFACE EXECUTE_INV_FFT
  MODULE PROCEDURE EXECUTE_INV_FFT_FLOAT
  MODULE PROCEDURE EXECUTE_INV_FFT_DOUBLE
END INTERFACE

PUBLIC PLAN_DIR_FFT, PLAN_INV_FFT

INTERFACE PLAN_DIR_FFT
  MODULE PROCEDURE PLAN_DIR_FFT_FLOAT
  MODULE PROCEDURE PLAN_DIR_FFT_DOUBLE
END INTERFACE

INTERFACE PLAN_INV_FFT
  MODULE PROCEDURE PLAN_INV_FFT_FLOAT
  MODULE PROCEDURE PLAN_INV_FFT_DOUBLE
END INTERFACE

INTEGER(C_INT8_T), POINTER :: FFTTMPBUFFER(:)


! ------------------------------------------------------------------
CONTAINS
! ------------------------------------------------------------------

SUBROUTINE EXECUTE_DIR_FFT_FLOAT(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,ALLOC,BUF)
  USE PARKIND_ECTRANS ,ONLY : JPIM

  IMPLICIT NONE

  REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_REAL(:)
  REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_COMPLEX(:)
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  TYPE(GROWING_ALLOCATION_TYPE), INTENT(IN) :: ALLOC
  TYPE(C_PTR), INTENT(IN) :: BUF
  INTERFACE
    SUBROUTINE EXECUTE_DIR_FFT_FLOAT_C(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,NFFT,ALLOC,BUF) BIND(C, name="execute_dir_fft_float")
      USE ISO_C_BINDING
      REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_REAL(:)
      REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_COMPLEX(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT
      TYPE(C_PTR), INTENT(IN), VALUE :: ALLOC
      TYPE(C_PTR), INTENT(IN), VALUE :: BUF
    END SUBROUTINE
  END INTERFACE

  !$ACC HOST_DATA USE_DEVICE(PREEL_REAL,PREEL_COMPLEX)
  CALL EXECUTE_DIR_FFT_FLOAT_C(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,SIZE(LOENS),C_LOC(ALLOC),BUF)
  !$ACC END HOST_DATA

END SUBROUTINE
SUBROUTINE EXECUTE_DIR_FFT_DOUBLE(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,ALLOC,BUF)
  USE PARKIND_ECTRANS ,ONLY : JPIM

  IMPLICIT NONE

  REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_REAL(:)
  REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_COMPLEX(:)
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  TYPE(GROWING_ALLOCATION_TYPE), INTENT(IN) :: ALLOC
  TYPE(C_PTR), INTENT(IN) :: BUF
  INTERFACE
    SUBROUTINE EXECUTE_DIR_FFT_DOUBLE_C(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,NFFT,ALLOC,BUF) BIND(C, name="execute_dir_fft_double")
      USE ISO_C_BINDING
      REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_REAL(:)
      REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_COMPLEX(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT
      TYPE(C_PTR), INTENT(IN), VALUE :: ALLOC
      TYPE(C_PTR), INTENT(IN), VALUE :: BUF
    END SUBROUTINE
  END INTERFACE

  !$ACC HOST_DATA USE_DEVICE(PREEL_REAL,PREEL_COMPLEX)
  CALL EXECUTE_DIR_FFT_DOUBLE_C(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,SIZE(LOENS),C_LOC(ALLOC),BUF)
  !$ACC END HOST_DATA

END SUBROUTINE

SUBROUTINE EXECUTE_INV_FFT_FLOAT(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,ALLOC,BUF)
  USE PARKIND_ECTRANS ,ONLY : JPIM

  IMPLICIT NONE

  REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_COMPLEX(:)
  REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_REAL(:)
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  TYPE(GROWING_ALLOCATION_TYPE), INTENT(IN) :: ALLOC
  TYPE(C_PTR), INTENT(IN) :: BUF
  INTERFACE
    SUBROUTINE EXECUTE_INV_FFT_FLOAT_C(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,NFFT,ALLOC,BUF) BIND(C, name="execute_inv_fft_float")
      USE ISO_C_BINDING
      REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_COMPLEX(:)
      REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_REAL(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT
      TYPE(C_PTR), INTENT(IN), VALUE :: ALLOC
      TYPE(C_PTR), INTENT(IN), VALUE :: BUF
    END SUBROUTINE
  END INTERFACE

  !$ACC HOST_DATA USE_DEVICE(PREEL_COMPLEX,PREEL_REAL)
  CALL EXECUTE_INV_FFT_FLOAT_C(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,SIZE(LOENS),C_LOC(ALLOC),BUF)
  !$ACC END HOST_DATA
END SUBROUTINE

SUBROUTINE EXECUTE_INV_FFT_DOUBLE(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,ALLOC,BUF)
  USE PARKIND_ECTRANS ,ONLY : JPIM

  IMPLICIT NONE

  REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_COMPLEX(:)
  REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_REAL(:)
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  TYPE(GROWING_ALLOCATION_TYPE), INTENT(IN) :: ALLOC
  TYPE(C_PTR), INTENT(IN) :: BUF
  INTERFACE
    SUBROUTINE EXECUTE_INV_FFT_DOUBLE_C(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,NFFT,ALLOC,BUF) BIND(C, name="execute_inv_fft_double")
      USE ISO_C_BINDING
      REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_COMPLEX(:)
      REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_REAL(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT
      TYPE(C_PTR), INTENT(IN), VALUE :: ALLOC
      TYPE(C_PTR), INTENT(IN), VALUE :: BUF
    END SUBROUTINE
  END INTERFACE

  !$ACC HOST_DATA USE_DEVICE(PREEL_COMPLEX,PREEL_REAL)
  CALL EXECUTE_INV_FFT_DOUBLE_C(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,SIZE(LOENS),C_LOC(ALLOC),BUF)
  !$ACC END HOST_DATA
END SUBROUTINE

FUNCTION PLAN_DIR_FFT_FLOAT(DUMMY,KFIELD,LOENS,OFFSETS,LALLOCATE)
  USE PARKIND_ECTRANS ,ONLY : JPIM, JPIB

  IMPLICIT NONE

  REAL(KIND=C_FLOAT), INTENT(IN) :: DUMMY
  INTEGER(KIND=JPIB),INTENT(IN)  :: PLAN_DIR_FFT_FLOAT
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  LOGICAL, INTENT(IN) :: LALLOCATE
  INTEGER :: IALLOCATE
  INTERFACE
    FUNCTION PLAN_DIR_FFT_FLOAT_C(KFIELD,LOENS,OFFSETS,NFFT,NALLOCATE) BIND(C, name="plan_dir_fft_float")
      USE ISO_C_BINDING
      INTEGER(KIND=C_SIZE_T) :: PLAN_DIR_FFT_FLOAT_C
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT,NALLOCATE
    END FUNCTION
  END INTERFACE

  IF (LALLOCATE) THEN
    IALLOCATE = 1
  ELSE
    IALLOCATE = 0
  ENDIF
  PLAN_DIR_FFT_FLOAT = PLAN_DIR_FFT_FLOAT_C(KFIELD,LOENS,OFFSETS,SIZE(LOENS),IALLOCATE)

END FUNCTION
FUNCTION PLAN_DIR_FFT_DOUBLE(DUMMY,KFIELD,LOENS,OFFSETS,LALLOCATE)
  USE PARKIND_ECTRANS ,ONLY : JPIM, JPIB

  IMPLICIT NONE

  REAL(KIND=C_DOUBLE), INTENT(IN) :: DUMMY
  INTEGER(KIND=JPIB),INTENT(IN)  :: PLAN_DIR_FFT_DOUBLE
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  LOGICAL, INTENT(IN) :: LALLOCATE
  INTEGER :: IALLOCATE
  INTERFACE
    FUNCTION PLAN_DIR_FFT_DOUBLE_C(KFIELD,LOENS,OFFSETS,NFFT,NALLOCATE) BIND(C, name="plan_dir_fft_double")
      USE ISO_C_BINDING
      INTEGER(KIND=C_SIZE_T) :: PLAN_DIR_FFT_DOUBLE_C
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT,NALLOCATE
    END FUNCTION
  END INTERFACE

  IF (LALLOCATE) THEN
    IALLOCATE = 1
  ELSE
    IALLOCATE = 0
  ENDIF
  PLAN_DIR_FFT_DOUBLE = PLAN_DIR_FFT_DOUBLE_C(KFIELD,LOENS,OFFSETS,SIZE(LOENS),IALLOCATE)

END FUNCTION

FUNCTION PLAN_INV_FFT_FLOAT(DUMMY,KFIELD,LOENS,OFFSETS,LALLOCATE)
  USE PARKIND_ECTRANS ,ONLY : JPIM, JPIB

  IMPLICIT NONE

  REAL(KIND=C_FLOAT), INTENT(IN) :: DUMMY
  INTEGER(KIND=JPIB),INTENT(IN)  :: PLAN_INV_FFT_FLOAT
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  LOGICAL, INTENT(IN) :: LALLOCATE
  INTEGER :: IALLOCATE
  INTERFACE
    FUNCTION PLAN_INV_FFT_FLOAT_C(KFIELD,LOENS,OFFSETS,NFFT,NALLOCATE) BIND(C, name="plan_inv_fft_float")
      USE ISO_C_BINDING
      INTEGER(KIND=C_SIZE_T) :: PLAN_INV_FFT_FLOAT_C
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT,NALLOCATE
    END FUNCTION
  END INTERFACE

  IF (LALLOCATE) THEN
    IALLOCATE = 1
  ELSE
    IALLOCATE = 0
  ENDIF
  PLAN_INV_FFT_FLOAT = PLAN_INV_FFT_FLOAT_C(KFIELD,LOENS,OFFSETS,SIZE(LOENS),IALLOCATE)
END FUNCTION

FUNCTION PLAN_INV_FFT_DOUBLE(DUMMY,KFIELD,LOENS,OFFSETS,LALLOCATE)
  USE PARKIND_ECTRANS ,ONLY : JPIM, JPIB

  IMPLICIT NONE

  REAL(KIND=C_DOUBLE), INTENT(IN) :: DUMMY
  INTEGER(KIND=JPIB),INTENT(IN)  :: PLAN_INV_FFT_DOUBLE
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  LOGICAL, INTENT(IN) :: LALLOCATE
  INTEGER :: IALLOCATE
  INTERFACE
    FUNCTION PLAN_INV_FFT_DOUBLE_C(KFIELD,LOENS,OFFSETS,NFFT,NALLOCATE) BIND(C, name="plan_inv_fft_double")
      USE ISO_C_BINDING
      INTEGER(KIND=C_SIZE_T) :: PLAN_INV_FFT_DOUBLE_C
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT,NALLOCATE
    END FUNCTION
  END INTERFACE

  IF (LALLOCATE) THEN
    IALLOCATE = 1
  ELSE
    IALLOCATE = 0
  ENDIF
  PLAN_INV_FFT_DOUBLE = PLAN_INV_FFT_DOUBLE_C(KFIELD,LOENS,OFFSETS,SIZE(LOENS),IALLOCATE)
END FUNCTION
END MODULE TPM_FFTC
